name: BoboBot
 
on:  workflow_dispatch

env:
  TYPE: build
  TZ: Asia/Manila
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 505600

    steps:
       - name: Checkouts
         uses: actions/checkout@master
     # Cleanup The Actions Workspace Using Custom Composite Run Actions
     #  - uses: rokibhasansagar/slimhub_actions@main

         
       - name: Initializing environment
         continue-on-error: true
         timeout-minutes: 100
         run: |
              sudo -E apt-get -qq update
              sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison ccache openjdk-8-jdk expect neofetch tmux tmate aria2
              git config --global user.name "spiderdev123"
              git config --global user.email "spidermanm7@hotmail.com"
              git clone --recurse-submodules https://github.com/spiderdev123/ErfanGSIs.git
              curl -sL https://git.io/file-transfer | sh
     
       - name: Setup Erfan Tools
         continue-on-error: true
         timeout-minutes: 10
         run: |
              sudo chmod -R 0777 ErfanGSIs
              sudo bash ErfanGSIs/setup.sh
       - name: Generate config.prop
         continue-on-error: true
         timeout-minutes: 3
         run: |
              java -jar Bobo.jar
         
       - name: Add values
         continue-on-error: true
         timeout-minutes: 1
         run: |
             rm -rf configs/config.prop && rm -rf configs/sf-creds.config
             cd configs
             touch config.prop
             echo "#BoÂ³+t config file" >> "config.prop"
             echo "#Tue Oct 18 08:08:12 KSA 2021" >> "config.prop"
             echo "bot-username=bobogsibot" >> "config.prop"
             echo "bot-token=${{ secrets.BOTKEY }}" >> "config.prop"
             echo "bot-master=5063902419" >> "config.prop"
             touch sf-creds.config
             echo "#Config file" >> "sf-creds.config"
             echo "#Tue Oct 18 08:08:12 KSA 2021" >> "sf-creds.config"
             echo "bot-sf-user=nippon" >> "sf-creds.config"
             echo "bot-send-announcement=true" >> "sf-creds.config"
             echo "bot-sf-proj=nippongsi" >> "sf-creds.config"
             echo "bot-announcement-id=-1001446520361" >> "sf-creds.config"
             echo "bot-sf-pass=${{ secrets.SFPASS }}" >> "sf-creds.config"
             echo "bot-sf-host=frs.sourceforge.net" >> "sf-creds.config"
       - name: Run Bot
         continue-on-error: true
         timeout-minutes: 310
         run: |
              sudo chmod -R 0777 *
              sudo java -jar Bobo.jar
